"""performance new  table

Revision ID: 07c0806bea4f
Revises: 32fd6032e693
Create Date: 2018-11-12 19:24:20.797852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c0806bea4f'
down_revision = '32fd6032e693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_performance_name'), 'performance', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_name'), table_name='performance')
    # ### end Alembic commands ###
