"""performance table

Revision ID: 32fd6032e693
Revises: 57977db74982
Create Date: 2018-11-12 19:20:07.445565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32fd6032e693'
down_revision = '57977db74982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('times', sa.DateTime(), nullable=True),
    sa.Column('theaters_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['theaters_id'], ['theaters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_description'), 'performance', ['description'], unique=True)
    op.create_index(op.f('ix_performance_times'), 'performance', ['times'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_times'), table_name='performance')
    op.drop_index(op.f('ix_performance_description'), table_name='performance')
    op.drop_table('performance')
    # ### end Alembic commands ###
