"""theaters table

Revision ID: 57977db74982
Revises: 
Create Date: 2018-11-12 18:58:07.341186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57977db74982'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theaters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theaters_address'), 'theaters', ['address'], unique=True)
    op.create_index(op.f('ix_theaters_name'), 'theaters', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_theaters_name'), table_name='theaters')
    op.drop_index(op.f('ix_theaters_address'), table_name='theaters')
    op.drop_table('theaters')
    # ### end Alembic commands ###
