"""Performance table

Revision ID: 8d5366be4c7f
Revises: 683a37c1356e
Create Date: 2018-11-13 15:19:49.160646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d5366be4c7f'
down_revision = '683a37c1356e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('main_actors', sa.String(length=180), nullable=True),
    sa.Column('theater_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['theater_id'], ['theater.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_time'), 'performance', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_time'), table_name='performance')
    op.drop_table('performance')
    # ### end Alembic commands ###
