"""performance table

Revision ID: b383d69992b0
Revises: f21355a87446
Create Date: 2018-11-12 22:15:56.080989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b383d69992b0'
down_revision = 'f21355a87446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('main_actors', sa.String(length=128), nullable=True),
    sa.Column('theaters_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['theaters_id'], ['theaters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_name'), 'performance', ['name'], unique=True)
    op.create_index(op.f('ix_performance_time'), 'performance', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_time'), table_name='performance')
    op.drop_index(op.f('ix_performance_name'), table_name='performance')
    op.drop_table('performance')
    # ### end Alembic commands ###
